use online_learning_and_progress_tracking_system;



-- Create Students Table
CREATE TABLE Students (
    student_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    enrollment_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert 100 unique student records
INSERT INTO Students (name, email) VALUES
('Alice Johnson', 'alice.johnson@example.com'),
('Bob Smith', 'bob.smith@example.com'),
('Cathy Nguyen', 'cathy.nguyen@example.com'),
('Daniel Lee', 'daniel.lee@example.com'),
('Evelyn Parker', 'evelyn.parker@example.com'),
('Frank Miller', 'frank.miller@example.com'),
('Grace Wilson', 'grace.wilson@example.com'),
('Hannah Moore', 'hannah.moore@example.com'),
('Isaac White', 'isaac.white@example.com'),
('Julia Kim', 'julia.kim@example.com'),
('Kevin Brown', 'kevin.brown@example.com'),
('Liam Harris', 'liam.harris@example.com'),
('Mia Clark', 'mia.clark@example.com'),
('Nathan Wright', 'nathan.wright@example.com'),
('Olivia Lewis', 'olivia.lewis@example.com'),
('Paul Walker', 'paul.walker@example.com'),
('Quinn Scott', 'quinn.scott@example.com'),
('Rachel Adams', 'rachel.adams@example.com'),
('Samuel Baker', 'samuel.baker@example.com'),
('Tina Young', 'tina.young@example.com'),
('Ursula Allen', 'ursula.allen@example.com'),
('Victor Hall', 'victor.hall@example.com'),
('Wendy King', 'wendy.king@example.com'),
('Xander Green', 'xander.green@example.com'),
('Yara Carter', 'yara.carter@example.com'),
('Zane Cooper', 'zane.cooper@example.com'),
('Aaron Hill', 'aaron.hill@example.com'),
('Beth Brooks', 'beth.brooks@example.com'),
('Chris Diaz', 'chris.diaz@example.com'),
('Diana Bennett', 'diana.bennett@example.com'),
('Ethan Murphy', 'ethan.murphy@example.com'),
('Fiona Howard', 'fiona.howard@example.com'),
('George Rogers', 'george.rogers@example.com'),
('Hailey Morgan', 'hailey.morgan@example.com'),
('Ian Foster', 'ian.foster@example.com'),
('Jack Reed', 'jack.reed@example.com'),
('Kelly Bell', 'kelly.bell@example.com'),
('Leo Hughes', 'leo.hughes@example.com'),
('Maya Rivera', 'maya.rivera@example.com'),
('Noah Gray', 'noah.gray@example.com'),
('Olive Patterson', 'olive.patterson@example.com'),
('Pete Price', 'pete.price@example.com'),
('Queenie Sanders', 'queenie.sanders@example.com'),
('Ryan Morris', 'ryan.morris@example.com'),
('Sophie Long', 'sophie.long@example.com'),
('Tom Butler', 'tom.butler@example.com'),
('Uma Barnes', 'uma.barnes@example.com'),
('Vera Powell', 'vera.powell@example.com'),
('Will Simmons', 'will.simmons@example.com'),
('Ximena Bryant', 'ximena.bryant@example.com'),
('Yusuf Shaw', 'yusuf.shaw@example.com'),
('Zara Cross', 'zara.cross@example.com'),
('Amber Perkins', 'amber.perkins@example.com'),
('Blake Collins', 'blake.collins@example.com'),
('Cara Evans', 'cara.evans@example.com'),
('Dean Ward', 'dean.ward@example.com'),
('Ella Torres', 'ella.torres@example.com'),
('Felix Peterson', 'felix.peterson@example.com'),
('Gina Edwards', 'gina.edwards@example.com'),
('Harold Fisher', 'harold.fisher@example.com'),
('Ivy Gonzales', 'ivy.gonzales@example.com'),
('Jake Russell', 'jake.russell@example.com'),
('Kara Hayes', 'kara.hayes@example.com'),
('Lydia Cole', 'lydia.cole@example.com'),
('Mason Powell', 'mason.powell@example.com'),
('Nina Barnes', 'nina.barnes@example.com'),
('Oscar Perry', 'oscar.perry@example.com'),
('Pamela Watson', 'pamela.watson@example.com'),
('Quincy Knight', 'quincy.knight@example.com'),
('Rose Bryant', 'rose.bryant@example.com'),
('Steve Ward', 'steve.ward@example.com'),
('Tara Cox', 'tara.cox@example.com'),
('Uriel Rogers', 'uriel.rogers@example.com'),
('Violet Lee', 'violet.lee@example.com'),
('Wesley Green', 'wesley.green@example.com'),
('Xena Clarke', 'xena.clarke@example.com'),
('Yvonne Franklin', 'yvonne.franklin@example.com'),
('Zack Hughes', 'zack.hughes@example.com'),
('Annie Wells', 'annie.wells@example.com'),
('Ben Gomez', 'ben.gomez@example.com'),
('Cory Roberts', 'cory.roberts@example.com'),
('Daisy Russell', 'daisy.russell@example.com'),
('Eric Bishop', 'eric.bishop@example.com'),
('Faith Patterson', 'faith.patterson@example.com'),
('Gabe Simpson', 'gabe.simpson@example.com'),
('Hope Simmons', 'hope.simmons@example.com'),
('Ivan Kelley', 'ivan.kelley@example.com'),
('Jackie Martin', 'jackie.martin@example.com'),
('Kenny Griffin', 'kenny.griffin@example.com'),
('Lara Kennedy', 'lara.kennedy@example.com'),
('Milo Murray', 'milo.murray@example.com'),
('Nellie Bailey', 'nellie.bailey@example.com'),
('Omar Woods', 'omar.woods@example.com'),
('Paige Walsh', 'paige.walsh@example.com'),
('Quinn Hill', 'quinn.hill@example.com'),
('Randy Bryant', 'randy.bryant@example.com'),
('Sara Chavez', 'sara.chavez@example.com'),
('Tyler Stevens', 'tyler.stevens@example.com'),
('Una Parker', 'una.parker@example.com'),
('Vivian Cruz', 'vivian.cruz@example.com'),
('Walter Myers', 'walter.myers@example.com'),
('Xavier Edwards', 'xavier.edwards@example.com'),
('Yasmin Turner', 'yasmin.turner@example.com'),
('Zoe Ford', 'zoe.ford@example.com');

select * from Students;